export enum Evaluations {
    PC1 = 'PC1',
    PC2 = 'PC2',
    PC3 = 'PC3',
    PC4 = 'PC4',
    PC5 = 'PC5',
    EXAM_PARCIAL = 'Examen Parcial',
    EXAM_FINAL = 'Examen Final',
    EXAM_1 = 'Examen 1',
    EXAM_2 = 'Examen 2',
    EXAM_3 = 'Examen 3',
    EXAM_4 = 'Examen 4',
    EXAM_ESPECIAL = 'Examen Especial',
    OPEN = 'Open',
}
